#!/bin/env sh
# first expression strips everything except k8s cluster context and namespace
# second expression strips timestamp before prompt symbol
gpaste-client get --use-index 0 | \
    sed \
    -e 's/^\(☸\ \S\+\ (.*)\)\ in.*/\1/g' \
    -e 's/^[0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}\ \(❯.*\)/\1/g'
