[battery]
disabled = true

[kubernetes]
disabled = false

[kubernetes.context_aliases]
'(?P<var_cluster>\w+)\.\w+\.\w+\.\w+' = '$var_cluster'

[aws]
disabled = true

[time]
disabled = false
format = '[$time]($style) '

[pulumi]
disabled = true

[localip]
disabled = true
