# See 'man zshbuiltins' and https://stackoverflow.com/a/30840986
# adds completion for git etc.
autoload -Uz compinit && compinit

export PATH="${HOME}/.local/bin:${HOME}/.cargo/bin:${PATH}"
eval "$(starship init zsh)"

# Adapt autosuggest color to Solarized
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=11"

export CASE_SENSITIVE="true"
export WORDCHARS='*?_[]~=&;!#$%^(){}'

# makes ctrl + u behave the same as bash (emacs)
bindkey "^u" backward-kill-line 

#ZSH customizations
setopt HIST_IGNORE_SPACE
setopt SHARE_HISTORY
export HISTFILE=~/.zsh_history
export SAVEHIST=50000
export WORDCHARS=''

# Make vim open files in tabs by default
alias vim="vim -p"
alias urldecode='python3 -c "import sys, urllib.parse as ul; print(\"\n\" + ul.unquote_plus(sys.argv[1]))"'
alias urlencode='python3 -c "import sys, urllib.parse as ul; print(\"\n\" + ul.quote_plus(sys.argv[1]))"'

# Variables
export VISUAL="vim"
export EDITOR="vim"

# LazyLoad the kubectl completion code for zsh into the current shell
function kubectl() {
    if ! type __start_kubectl &> /dev/null ; then
        source <(command kubectl completion zsh)
    fi

    command kubectl "$@"
}

# Put machine specific stuff here
if [[ -f ~/.zshrc.custom ]] ; then
    source ~/.zshrc.custom
fi

source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# opam configuration
test -r /home/rbjorklin/.opam/opam-init/init.zsh && . /home/rbjorklin/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
