source ~/.antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions

# Adapt autosuggest color to Solarized
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE=fg=11

# makes ctrl + u behave the same as bash (emacs)
bindkey "^u" backward-kill-line 

# Load the theme.
antigen theme rbjorklin/rbjorklin-zsh-theme

# Tell Antigen that you're done.
antigen apply

# Make vim open files in tabs by default
alias vim="vim -p"
alias urldecode='python3 -c "import sys, urllib.parse as ul; print(\"\n\" + ul.unquote_plus(sys.argv[1]))"'
alias urlencode='python3 -c "import sys, urllib.parse as ul; print(\"\n\" + ul.quote_plus(sys.argv[1]))"'

# Variables
export VISUAL="vim"
export EDITOR="vim"
export DOCKER_HOST=tcp://localhost:2375

# LazyLoad the kubectl completion code for zsh into the current shell
function kubectl() {
    if ! type __start_kubectl &> /dev/null ; then
        source <(command kubectl completion zsh)
    fi

    command kubectl "$@"
}

# opam configuration
test -r ~/.opam/opam-init/init.zsh && . ~/.opam/opam-init/init.zsh &> /dev/null || true

# Put machine specific stuff here
if [[ -f ~/.zshrc.custom ]] ; then
    source ~/.zshrc.custom
fi
