[general]
live_config_reload = true
working_directory = "None"
import = [
  "themes/selenized-black.toml"
]

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[colors.cursor]
cursor = "0x839496"
text = "0x002b36"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[font]
size = 15.0

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

# https://github.com/neovim/neovim/issues/20126#issuecomment-1296039900
# https://github.com/tmux/tmux/issues/2705#issuecomment-1518520942
# https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_(Control_Sequence_Introducer)_sequences
# https://gist.github.com/ConnerWill/d4b6c776b509add763e17f9f113fd25b#keyboard-strings
# Make "C-i" send "F12 Tab". Then from tmux we send the `CSI u`-encoded
# version of "C-i" ("\x1b[105;5u").
[[keyboard.bindings]]
#chars = "\u001B[24~\t" # '\u001B' is Escape, '24' is F12, '\t' is Tab
#chars = "\u001B[105;5u" # '\u001B' is Escape, '105' is 'I', 'u' terminates the escape sequence
chars = "î"
key = "I"
mods = "Control"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 200
lines = 63

[window.padding]
x = 0
y = 0
